name: Server

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

defaults:
  run:
    working-directory: server

jobs:
  push_schema:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: yarn install
      - name: Push schema
        run: yarn apollo service:push --graph=ludum-lite --key=${{ secrets.APOLLO_STUDIO_KEY }} --variant=current --localSchemaFile=./src/__generated__/schema.graphql
